//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new exercise.
        /// </summary>
        internal static string Add_new_exercise_button {
            get {
                return ResourceManager.GetString("Add_new_exercise_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new training plan.
        /// </summary>
        internal static string Add_new_training_plan_button {
            get {
                return ResourceManager.GetString("Add_new_training_plan_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create exercise.
        /// </summary>
        internal static string Create_Exercise_Button {
            get {
                return ResourceManager.GetString("Create_Exercise_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new exercise.
        /// </summary>
        internal static string Create_Exercise_Page_Title {
            get {
                return ResourceManager.GetString("Create_Exercise_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create training plan.
        /// </summary>
        internal static string Create_Training_Plan_Button {
            get {
                return ResourceManager.GetString("Create_Training_Plan_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new training plan.
        /// </summary>
        internal static string Create_Training_Plan_Page_Title {
            get {
                return ResourceManager.GetString("Create_Training_Plan_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete_Button {
            get {
                return ResourceManager.GetString("Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description_label_double_quote {
            get {
                return ResourceManager.GetString("Description_label_double_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of exercise.
        /// </summary>
        internal static string Detail_Exercise_Page_Title {
            get {
                return ResourceManager.GetString("Detail_Exercise_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new exercise description.
        /// </summary>
        internal static string Enter_new_exercise_description {
            get {
                return ResourceManager.GetString("Enter_new_exercise_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter exercise name.
        /// </summary>
        internal static string Enter_new_exercise_name {
            get {
                return ResourceManager.GetString("Enter_new_exercise_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter training plan name.
        /// </summary>
        internal static string Enter_new_training_plan_name {
            get {
                return ResourceManager.GetString("Enter_new_training_plan_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Exercise_List_Page_Title {
            get {
                return ResourceManager.GetString("Exercise_List_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_label_double_quote {
            get {
                return ResourceManager.GetString("Name_label_double_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save exercise.
        /// </summary>
        internal static string Save_Exercise_Button {
            get {
                return ResourceManager.GetString("Save_Exercise_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Page_Title {
            get {
                return ResourceManager.GetString("Settings_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plans.
        /// </summary>
        internal static string Training_Plans_Page_Title {
            get {
                return ResourceManager.GetString("Training_Plans_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User_Page_Title {
            get {
                return ResourceManager.GetString("User_Page_Title", resourceCulture);
            }
        }
    }
}
