//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exercise to training.
        /// </summary>
        internal static string Add_Exercise_To_Training {
            get {
                return ResourceManager.GetString("Add_Exercise_To_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exercise to training.
        /// </summary>
        internal static string Add_Exercise_To_Training_Page_Title {
            get {
                return ResourceManager.GetString("Add_Exercise_To_Training_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exercise.
        /// </summary>
        internal static string Add_new_exercise {
            get {
                return ResourceManager.GetString("Add_new_exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new exercise.
        /// </summary>
        internal static string Add_new_exercise_button {
            get {
                return ResourceManager.GetString("Add_new_exercise_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pause.
        /// </summary>
        internal static string Add_new_pause {
            get {
                return ResourceManager.GetString("Add_new_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new training.
        /// </summary>
        internal static string Add_new_training_button {
            get {
                return ResourceManager.GetString("Add_new_training_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new training plan.
        /// </summary>
        internal static string Add_new_training_plan_button {
            get {
                return ResourceManager.GetString("Add_new_training_plan_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create exercise.
        /// </summary>
        internal static string Create_Exercise_Button {
            get {
                return ResourceManager.GetString("Create_Exercise_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new exercise.
        /// </summary>
        internal static string Create_Exercise_Page_Title {
            get {
                return ResourceManager.GetString("Create_Exercise_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pause.
        /// </summary>
        internal static string Create_Pause_Button {
            get {
                return ResourceManager.GetString("Create_Pause_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pause.
        /// </summary>
        internal static string Create_Pause_Page_Title {
            get {
                return ResourceManager.GetString("Create_Pause_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create training.
        /// </summary>
        internal static string Create_Training_Button {
            get {
                return ResourceManager.GetString("Create_Training_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Training.
        /// </summary>
        internal static string Create_Training_Page_Title {
            get {
                return ResourceManager.GetString("Create_Training_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create training plan.
        /// </summary>
        internal static string Create_Training_Plan_Button {
            get {
                return ResourceManager.GetString("Create_Training_Plan_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new training plan.
        /// </summary>
        internal static string Create_Training_Plan_Page_Title {
            get {
                return ResourceManager.GetString("Create_Training_Plan_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete_Button {
            get {
                return ResourceManager.GetString("Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description_label_double_quote {
            get {
                return ResourceManager.GetString("Description_label_double_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Duration_label_double_quote {
            get {
                return ResourceManager.GetString("Duration_label_double_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit exercise in training.
        /// </summary>
        internal static string Edit_Exercise_In_Training_Page_Title {
            get {
                return ResourceManager.GetString("Edit_Exercise_In_Training_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of exercise.
        /// </summary>
        internal static string Edit_Exercise_Page_Title {
            get {
                return ResourceManager.GetString("Edit_Exercise_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pause.
        /// </summary>
        internal static string Edit_Pause_Button {
            get {
                return ResourceManager.GetString("Edit_Pause_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pause.
        /// </summary>
        internal static string Edit_Pause_Page_Title {
            get {
                return ResourceManager.GetString("Edit_Pause_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of training.
        /// </summary>
        internal static string Edit_Training_Page_Title {
            get {
                return ResourceManager.GetString("Edit_Training_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of training plan.
        /// </summary>
        internal static string Edit_TrainingPlan_Page_Title {
            get {
                return ResourceManager.GetString("Edit_TrainingPlan_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter exercise time duration.
        /// </summary>
        internal static string Enter_exercise_seconds {
            get {
                return ResourceManager.GetString("Enter_exercise_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string Enter_new_description {
            get {
                return ResourceManager.GetString("Enter_new_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter exercise description.
        /// </summary>
        internal static string Enter_new_exercise_description {
            get {
                return ResourceManager.GetString("Enter_new_exercise_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter exercise name.
        /// </summary>
        internal static string Enter_new_exercise_name {
            get {
                return ResourceManager.GetString("Enter_new_exercise_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pause description.
        /// </summary>
        internal static string Enter_new_pause_description {
            get {
                return ResourceManager.GetString("Enter_new_pause_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pause duration.
        /// </summary>
        internal static string Enter_new_pause_duration {
            get {
                return ResourceManager.GetString("Enter_new_pause_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pause name.
        /// </summary>
        internal static string Enter_new_pause_name {
            get {
                return ResourceManager.GetString("Enter_new_pause_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter training plan description.
        /// </summary>
        internal static string Enter_new_training_plan_description {
            get {
                return ResourceManager.GetString("Enter_new_training_plan_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter training plan name.
        /// </summary>
        internal static string Enter_new_training_plan_name {
            get {
                return ResourceManager.GetString("Enter_new_training_plan_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pause duration in seconds.
        /// </summary>
        internal static string Enter_pause_duration {
            get {
                return ResourceManager.GetString("Enter_pause_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reps.
        /// </summary>
        internal static string Enter_reps {
            get {
                return ResourceManager.GetString("Enter_reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter rest time.
        /// </summary>
        internal static string Enter_rest_duration {
            get {
                return ResourceManager.GetString("Enter_rest_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter rest time duration.
        /// </summary>
        internal static string Enter_rest_seconds {
            get {
                return ResourceManager.GetString("Enter_rest_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sets.
        /// </summary>
        internal static string Enter_sets {
            get {
                return ResourceManager.GetString("Enter_sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight.
        /// </summary>
        internal static string Enter_weight {
            get {
                return ResourceManager.GetString("Enter_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Exercise_List_Page_Title {
            get {
                return ResourceManager.GetString("Exercise_List_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps:.
        /// </summary>
        internal static string Label_Reps {
            get {
                return ResourceManager.GetString("Label_Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Label_Seconds {
            get {
                return ResourceManager.GetString("Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets:.
        /// </summary>
        internal static string Label_Sets {
            get {
                return ResourceManager.GetString("Label_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string Label_Weight {
            get {
                return ResourceManager.GetString("Label_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_label_double_quote {
            get {
                return ResourceManager.GetString("Name_label_double_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick exercise.
        /// </summary>
        internal static string Pick_Exercise {
            get {
                return ResourceManager.GetString("Pick_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick exercise.
        /// </summary>
        internal static string Pick_Exercise_label {
            get {
                return ResourceManager.GetString("Pick Exercise_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Prompt_Are_you_sure {
            get {
                return ResourceManager.GetString("Prompt_Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Prompt_Cancel {
            get {
                return ResourceManager.GetString("Prompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Prompt_confirm {
            get {
                return ResourceManager.GetString("Prompt_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create copy.
        /// </summary>
        internal static string Prompt_Create_copy {
            get {
                return ResourceManager.GetString("Prompt_Create_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Prompt_Delete {
            get {
                return ResourceManager.GetString("Prompt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Prompt_Edit {
            get {
                return ResourceManager.GetString("Prompt_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercise.
        /// </summary>
        internal static string Prompt_exercise {
            get {
                return ResourceManager.GetString("Prompt_exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise options.
        /// </summary>
        internal static string Prompt_Exercise_options {
            get {
                return ResourceManager.GetString("Prompt_Exercise_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        internal static string Prompt_pause {
            get {
                return ResourceManager.GetString("Prompt_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove .
        /// </summary>
        internal static string Prompt_Remove {
            get {
                return ResourceManager.GetString("Prompt_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training.
        /// </summary>
        internal static string Prompt_training {
            get {
                return ResourceManager.GetString("Prompt_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training options.
        /// </summary>
        internal static string Prompt_Training_options {
            get {
                return ResourceManager.GetString("Prompt_Training_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plan.
        /// </summary>
        internal static string Prompt_Training_plan {
            get {
                return ResourceManager.GetString("Prompt_Training_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training plan.
        /// </summary>
        internal static string Prompt_training_plan_ {
            get {
                return ResourceManager.GetString("Prompt_training_plan_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plan options.
        /// </summary>
        internal static string Prompt_Training_plan_options {
            get {
                return ResourceManager.GetString("Prompt_Training_plan_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep duration.
        /// </summary>
        internal static string Rep_duration_label {
            get {
                return ResourceManager.GetString("Rep_duration_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest after last set.
        /// </summary>
        internal static string Rest_after_last_set_label {
            get {
                return ResourceManager.GetString("Rest_after_last_set_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest duration.
        /// </summary>
        internal static string Rest_duration_label {
            get {
                return ResourceManager.GetString("Rest_duration_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save exercise.
        /// </summary>
        internal static string Save_Exercise_Button {
            get {
                return ResourceManager.GetString("Save_Exercise_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save training.
        /// </summary>
        internal static string Save_Training_Button {
            get {
                return ResourceManager.GetString("Save_Training_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save training plan.
        /// </summary>
        internal static string Save_TrainingPlan_Button {
            get {
                return ResourceManager.GetString("Save_TrainingPlan_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Page_Title {
            get {
                return ResourceManager.GetString("Settings_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plan.
        /// </summary>
        internal static string Training_List_Page_Title {
            get {
                return ResourceManager.GetString("Training_List_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plans.
        /// </summary>
        internal static string Training_Plans_Page_Title {
            get {
                return ResourceManager.GetString("Training_Plans_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User_Page_Title {
            get {
                return ResourceManager.GetString("User_Page_Title", resourceCulture);
            }
        }
    }
}
